### ISSUE TITLE
Request for a Planned Feature Roadmap/Log

### ISSUE THREAD

**Issue by jasondavis** [paperwork/paperwork#189]
I know that GitHub issues are amazing and really design well and that there is an appropriate "Enhancement" Label already, however...

The other day I had just discovered the application which really made my day!  I instantly jumped in playing with it and seeing what I loved about it and what I felt it still lacked to be my DREAM Evernote replacement.  I without hesitation rushed and posted a request of features on this Issue tracker prematurely!  Within an hour of posting and reading other issues spread across 3-4 pages, I realized that more than half of my request had been mentioned already!  It was too late though I had already made my post!  

So what I would really like to see for myself and to help countless other fans and contributors is an on-going updated Document that could hold like a Road Map of features that had been thugh of and basically "Approved" as something that "we" (we meaning whoever the Developers are) are planning to implement.  This would make a nice quick and easy way to see the already planned features all in 1 easy to access and read at glance place!

I feel every awesome and large piece of software that's being developed should have such a Road Map Document and many of them do, maybe it's just me but I feel some others would agree and enjoy it as well?

 If this Road Map is built, it could even link to Issues related to some of the features where the on-going discussion and comments could continue to be held on each item as the Road Map is simply a curated list of the "approved" or "planned" features.  

One more thing that some other projects do is add a Label to the Issue tracker for "Planned" and/or "Approved" as that then lets you basically sort and filter by those tags and that sort of automatically builds the "Road Map LIst" as well.

Thanks for reading, can't wait to see what PaperWork evolves  into!

.

**Comment by devilx** [comment]
Thank you for your feedback!

A few months ago, Paperwork used a publicly visible Trello board to organise features. Back then, I was the only one using it, because I was still the only one on the project. In order to make it more easy for others to get into development, I then migrated everything into GitHub issues.

However, right now, there is a milestone available here on GitHub issues: https://github.com/twostairs/paperwork/milestones/Paperwork%201.0

So far I've added the most relevant things to this milestone. Of course, any of you is free to extend it. My suggestion would be to start by adding every issue that needs to be fixed/implemented to the Paperwork 1.0 milestone. By that, we don't need some sort of additional "approved" or "planned" label, as the people would see what's planned by simply browsing the milestone.

On a next step, we could add more milestones (Paperwork 1.1, Paperwork 1.2, etc.) and add all other issues which aren't relevant for the first official release of Paperwork to later versions.

I would personally like to keep the planning as simple and transparent as possible. I even thought about integrating some sort of "Feedback" dialog directly into Paperwork, which would create issues through the GitHub API - unfortunately there's no way to create "anonymous" issues. Regarding the duplicates: I don't see this as such a big problem. Closing them doesn't take a lot of time and even duplicates might contain new ideas.

@Liongold @joshlemer @Baldrs what do you guys think?

**Comment by Baldrs** [comment]
@devilx we can continue to use the issues while providing some document with generalization of the issues and some plans and goals. It will help even as to understand what to do in some way. Setting goals, I think, is important, and most important thing is to record what do we want to see in Paperwork 1.0, ie to have better and more than in evernote functions, write a pair of clippers, have markdown, etc.

So yes, lets figure out the goals and record them.

**Comment by jasondavis** [comment]
great +1

**Comment by devilx** [comment]
Okay guys. I've now created milestones for Paperwork 2.0, 3.0 and 4.0 as well. Also, I went through all our issues and tried to assign milestones in a way it made sense to me. If you should see anything wrong with the assignments make sure to comment/re-assign.

Every new issue/enhancement that we (or other users) will come up with should be assigned to a milestone, as soon as it's clear that it should be implemented.

The general plan I followed while assigning all the issue was:
1.0: Fix teething troubles, implement *basic* features and make Paperwork usable/installable by the average Joe.
2.0: Implement more advance features, that would bring Paperwork to approximately the same level as commercial products (Evernote, OneNote, etc.)
3.0: Put Paperwork on steroids with features, that would definitely attract people's attention away from commercial products
4.0: continue the saga ;-)
...

Now, to clarify versioning: Releases won't come out like *1.0 this summer, 2.0 this winter, 3.0 next summer*, but be more like *1.0 until the end of Q4/15, 1.1 Q1/16, 1.2 Q2/16, etc.*. Things really need to be tested extensively until new experimental features will find their ways into Paperwork.

However, what do you think? Is this kind of planning enough for now?

**Comment by Liongold** [comment]
I very much like this idea (and its implementation). I don't think a release date is suitable for now but then we organise a meeting (we = all developers and/or interested parties) discuss about a possible release date, considering the progress done.

**Comment by mrusme** [comment]
v2 has this in place now.
