### ISSUE TITLE
HTML Source View/Edit Mode

### ISSUE THREAD

**Issue by jasondavis** [paperwork/paperwork#190]
As part of my bigger first issue post I had mentioned in my list that I would like to be able to edit the HTML from the Source.  My reason is mainly to adjust things as copy/pasting content into WYSIWYG style editors generally works about 90% how I would like it to but there is always that 10% where I WISH I could simply access the source code and "fix" spacing issues or whatever the issue is!

As an example, in a WordPress editor you always have the WYSIWYG view and clicking a Tab gives you access to the generated Source HTML!  

I was looking at ckeditor as I saw that is what is being used in PaerWork right now.  I was happy to see that this exact feature ships with the default ckeditor editor!  It seems you have removed the button to access the feature, perhaps even the code for it?  With that said, it sounds like it would be easy to add back in if that decision was ever made =)

@devilx had mentioned in response to this request before...  
 "HTML support isn't planned yet (as it would be hard for us to validate and fix it, in order to avoid the user breaking the whole web-ui by writing malformed HTML code)"

In response to that comment.  What if the View Source button or access was kept as an "Advanced user" feature?  So basically it could be hidden and then to gain access to this feature I have 2 ideas that might would help?...
- Have a setting/option in the admin or elsewhere to enable/disable it...maybe even on a per user basis!  
- Without adding an option, reveal/hide the view source button with a keyboard combination

I know there is the MarkDown request.  I am a big MarkDown fan and user however to me, to be honest thge WYSIWYG ediotr works just fine.  Markdown simply converts it;s own form of a BBCode to HTML just as ckeditor converts to HTML so to me I see no real gain by switching from ckeditor to markdown!  That's just my opinion on the subject.

**Comment by devilx** [comment]
@jasondavis thanks for writing. Basically, you quoted the most important thing: Validation. Indeed, we use CKEdtior which provides a Source-View by default and it wouldn't take a big amount of work to make this configurable, so that users could turn on an "advanced mode" within their settings. The only thing I'm still seeing as a big problem is the validation issue. From what I know, WordPress has some integrated HTML validation (and even correction), in order to not let the user totally screw up his blog/site. This is something we (right now) don't have at all.

In addition to that, with allowing the user to modify the pure HTML, some smaller tasks pop-up as well. For example, we would need to enhance the content_preview "parser" (which, right now, isn't a parser at all and only takes the content and writes it into the content_preview field as well), in order to show something that makes sense within the notes list.

Therefor, yes, I believe we could build in source code editing, but if we do, it should be done the right way and not only by including CKEditor's source-view plugin.

**Comment by joshlemer** [comment]
@devilx @jasondavis Posting this here, I asked this in the Gitter chat but just for visibility:

What do you guys think about this:

Have Markdown notes and have WYSIWYG notes, but we don't have to provide WYSIWYG <-> Markdown conversion. This would greatly simplify the issue, and having a markdown editor seems to me to be a very important feature for a lot of users.

I'm not sure how it would work 100% in terms of User Interface. Like if it would prompt them to choose WYSIWYG/Markdown when creating a new note, or if there would be separate buttons to create a new WYSIWYG/Markdown note, or if users could set a default note type.

**Comment by devilx** [comment]
Quoting what I wrote on Gitter:

> ... came up with an idea to include a new column "type" within the notes-table, that defines the note type. I think, this is pretty much the best way we could solve the WYSIWYG/Markdown/whatever issue.
Adding a column "type" which preferably is a fixed with char (not an integer id!).

**Comment by Baldrs** [comment]
I agree with @joshlemer, type serves just right, and we can use as many different editors as we want.

But for some formats, like for markdown, the source differs from the representation, and it is highly inefficient to have it recompiled every time it is accessed, so I propose(and @devilx already proposed this earlier), to have additional column with the resulting representation.
