### ISSUE TITLE
Plugins interface / API

### ISSUE THREAD

**Issue by mrusme** [paperwork/paperwork#223]
We need to think of a way for implementing a plugins interface/API in order to allow other devs to easily extend Paperwork without modifying its core. Here are some requirements:

Plugins should be placed into a specific subfolder within Paperwork. Every plugin should contain of only one base folder with all plugin code and data inside. The tricky part is, that nothing but the /public folder is accessible via web, meaning that putting the plugins folder into any parent directory of public would make it impossible for the plugin to serve its own CSS/JS. One solution to this would be the inclusion of a gulp task that automagically goes through the plugins folder and builds all assets to the public directory. Then Paperwork would take care of including them properly. They could even be built right into the Paperwork assets, in order to reduce requests count.

Regarding the plugins interface / api itself, Paperwork would need to provide hooks for every action that the user could trigger through the user interface. I'm not sure how a plugin could extend Paperwork AngularJS code, but I think there should be a way by using broadcasts. Someone who already built some plugins interface in AngularJS could probably plan this through in deeper detail.

However, we need to keep in mind that Paperwork contains of three parts: The web-ui (blade templates, angular code; front-end), the actual core (middle-ware) and the database (back-end). Plugins should only extend the front-end part of Paperwork, meaning they theoretically no PHP programming knowledge should be needed for developing Paperwork plugins. For the middle-ware part, I don't see any need to provide a plugin-capability. What will be needed though, would be some sort of "plugin settings" API (probably something the user-settings could be extended towards), in order to allow the plugin to save and load certain data.

In order for all this to work, plugins will need a unique identifier, which I'm not sure yet how to be generated. Paperwork could generate a UUID for every new plugin that can be found within the plugins-directory. Or plugins could provide an identifier on their own (e.g. com.yeah.superplugin), although nobody could assure for these to be unique.

Thoughts?

**Comment by Liongold** [comment]
About including assets, I suggest having a sort of manifest file for each plugin that includes all files needed for the plugin to work. Another way could be a function to be used in the plugin, like loadCSS() but that would require scanning the code to load the files during load. 

About id, I think an identifier could be good but there should be some sort of developer access to make sure these remain uique. These are just my initial thoughts. All feedback is welcome.

**Comment by devilx** [comment]
I like the manifest idea. Some description file would indeed save us a lot of "blind scanning". :+1:

**Comment by Baldrs** [comment]
First of all, we have quite a complex situation here. We have backend and a frontend tied to it, but also we will have platform clients in near future, so what will be the plugin in fist place? It seems every desktop/mobile app would re-invent the every web-frontend plugin or the plugins will be backend-only?

Regarding the web part:  Will it unite backend and frontend features or there will be separation? Will the js/css/less/etc compiled and aggregated by the core or with gulp? Changing of the way assets are added and served requires complex changes in everything, and I don't think we can just `system('gulp')` on asset change because not everybody will be happy with nodejs on server running php applications(although many have, for example wikipedia's new fancy WYSIWYG editor uses is as backend).
