### ISSUE TITLE
Write user help

### ISSUE THREAD

**Issue by mrusme** [paperwork/paperwork#29]
The user help should be written. The format for that is regular markdown with some specialities regarding URLs. Please refer to the current help page, to get more info.

**Comment by SquirrelNinja** [comment]
Hi,
I came across this project looking for an Evernote alternative.  My background is Software Engineering.  I would be happy to help document how this tool works, and then once I understand it, perhaps would have time to write some code.  I have limited PHP experience, but can code in C, C++, Java, Ruby, Groovy and probably some others that have fallen by the wayside, so what's anther language?
Ping me if you are interested....

**Comment by devilx** [comment]
@SquirrelNinja sure we are! Right now, there's already some technical information about setting up Paperwork on your own machine located within our Wiki: https://github.com/twostairs/paperwork/wiki

Regarding this issue here: As soon as you got your own Paperwork installation running, you might want to check out ```paperwork/frontend/app/help/```, where there should be several index.<locale>.md files. These files document the basics on how the documentation you can reach via through the /help URL work.

Now, for creating the user-documentation, the index files need to be altered in order to provide an actual index of all help topics available. Every topic should go into own <topic>.<locale>.md files. These files could even be organized using sub-folders, if needed.

Within these files documentation can be written using regular markdown. There are some special features that have been documented inside the index.<locale>.md placeholders:

> # Help
>
> Welcome to Paperwork! Here is, where the help is going to be. We introduced a few specialities to the > Markdown used to generate this help pages from:
> 
> * Help URLs: For linking to other help pages, simply use the following format: `[this is a link](@help.folder.anotherfolder.file)`
> * Help images: For displaying images that are stored in the public/images/help/-folder, use this: `![my image](@image.ay-caramba.png "Ay caramba!")`

That's pretty much everything needed to know about user help. :-)

**Comment by SquirrelNinja** [comment]
Hi,
I'm working on the install now.  BTW - on the github page, the link to
composer takes you somewhere very bad... You should probably look at it...

Cheers,
Chuck

**Comment by ChrisLahaye** [comment]
@SquirrelNinja Thanks for mentioning this, created a pull request with the correct domain (#232)

**Comment by devilx** [comment]
:+1:
