### ISSUE TITLE
Fix mobile web-ui

### ISSUE THREAD

**Issue by mrusme** [paperwork/paperwork#46]
The mobile web-ui currently doesn't neither look nor work the way it should. While browsing from a smartphone, Paperwork should be acting a lot more like a native app. Not sure yet, what the best ui design for this would be, though. It even might be better to use Polymer (or something else) instead of pure Bootstrap to build the mobile UI, although this would result in having a separate mobile layout.

Good ideas, anyone?

**Comment by yuchi** [comment]
What about writing a native app? With Titanium SDK it could be relatively easy.

**Comment by Liongold** [comment]
There are already plans for it.

**Comment by devilx** [comment]
@yuchi it would be very nice to have native mobile apps, of course. One could think for utilising Mono/Xamarin for that, in order to keep the "development costs" low.

Yet, the team is pretty small and we're not having the capacity of already providing the full stack of applications. If you (or anyone else) have ambitions in that direction, feel free to join the Paperwork team and plan these with us. :)

**Comment by jamesrascal** [comment]
@devilx  - The biggest thing that is broken in the mobile UI is the missing save icon. You can see a note and read notes but trying to edit or add a new note is impossible.
