### ISSUE TITLE
Cannot redeclare class illuminate\support\classloader in ClassLoader.php

### ISSUE THREAD

**Issue by f-thiele** [paperwork/paperwork#577]
Hi,

while trying to setup my first instance of paperwork and following the [initial installation guide](https://github.com/twostairs/paperwork/wiki/Initial-installation) I'm running into a blank page with my log file giving the following error:

(_www.example.com and IP-adress are anonymized through me_)

`2016/01/01 11:41:46 [error] 13288#0: *2968 FastCGI sent in stderr: "PHP message: PHP Fatal error:  include(): Cannot redeclare class illuminate\support\classloader in /var/www/paperwork/frontend/vendor/composer/ClassLoader.php on line 412" while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: www.example.com, request: "GET /paperwork/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "www.example.com"`

I am running an nginx server with a subfolder configuration for paperwork and following the [documentation](https://github.com/twostairs/paperwork/wiki/Running-paperwork-in-subfolder) I could find, the corresponding part in my configuration file is:

```
location ^~ /paperwork {
    alias /var/www/paperwork/frontend/public/;
    try_files $uri $uri/ @paperwork;

    access_log /var/log/paperwork.access.log;
    error_log /var/log/paperwork.error.log;

    location ~* \.php {
            include /etc/nginx/fastcgi_params;
            fastcgi_index index.php;

            fastcgi_split_path_info ^(.+\.php)(.*)$;
            fastcgi_pass unix:/var/run/php5-fpm.sock;
    }
}

location @paperwork {
    rewrite ^/paperwork/(.*)$ /paperwork/index.php/$1 last;
}
```

Am I missing something obvious here, that prevents me from running paperwork? Or does anyone else run into this problem?

Thank you and best wishes!

**Comment by Liongold** [comment]
Do you have all composer dependencies installed? Also do you have php5-fpm installed, please?

**Comment by Liongold** [comment]
Also are you accessing Paperwork from a subdomain?

**Comment by workboot** [comment]
Thank you for your replies. The composer installer said: "All settings correct for using Composer". I am running php5-fpm on other projects of mine so far without problems.

My nginx configuration is all running on one domain: www.example.com. In different subfolders however I run different applications similar to the [subfolder documentation of paperwork](https://github.com/twostairs/paperwork/wiki/Running-paperwork-in-subfolder) so that I have www.example.com/appA and www.example.com/appB for instance.

After removing all files and folders and start the procedure again from the git clone it now shows me the setup wizard. However when trying to register the first user account or when changing the configuration settings within the wizard the buttons are non functional and I see in the console a **500 status code** for
* https://www.example.com/paperwork/install/registeradmin
* https://www.example.com/paperwork/install/configurate

respectively. The reason for this seems to lay according to the logs in:

````rewrite or internal redirection cycle while redirect to named location "@paperwork" , client: xxx.xxx.xxx.xxx, server: www.example.com, request: "POST /paperwork/install/registeradmin HTTP/1.1", host: "www.example.com", referrer: "https://www.example.com/paperwork/" ````

Probably this indicates a missing ressource resulting in a loop or a faulty nginx configuration, which I fail to spot so far as it follows the [subfolder documentation of paperwork](https://github.com/twostairs/paperwork/wiki/Running-paperwork-in-subfolder)

If requested (and helpful), I could certainly paste the output that I received from all the commands described in the initial installation wiki document.

**Comment by Liongold** [comment]
Sorry for the late reply. Can you try accessing it without a subfolder structure please and show your result, please?

**Comment by Liongold** [comment]
So as `example.com` without the `/paperwork` part.
