### ISSUE TITLE
Client-side caching & push refreshes

### ISSUE THREAD

**Issue by mrusme** [paperwork/paperwork#59]
Currently, on every click, for example on a notebook, an API call is being executed, that gets the latest data from within that notebook and displays it in form of a notes list. This leads to quite some delay while browsing through a thinner network connection (e.g. a tethered phone on 3G).

A better way to solve this would be to allow client-side caching of notebook/note/version-data and only update these caches when the Paperwork server says there's new data available. For this purpose, some sort of Comet service needs to be implemented.

One possibility would be to have a node.js service running behind the apache/nginx (reverse-proxyed) where the frontend connects to via [socket.io](https://github.com/Automattic/socket.io) to the service and receives "pings" as soon as new data is available for that user (e.g. he changed some note on another device, or someone added a new note to a shared notebook, as soon as #18 and #26 was implemented). Then, the current client-side browser cache could be dismissed and a new API call could fetch the latest data.

Thoughts?

**Comment by Liongold** [comment]
Do you really think adding a node.js requirement is required for this?

**Comment by devilx** [comment]
@Liongold it's not required, but I don't know of any other read-to-use Comet-like setup that would be more convenient. With Socket.io the "push"-part would work out of the box. And it would be lot easier to set up and maintain than by using APE-Project or any other. Besides, we already have a ton of JavaScript onboard - Node.js wouldn't be as much of "another tech" within Paperwork.

However, I'm not settled for the Node.js/Socket.io setup. If you/anyone knows a better way, I'd be happy to hear. Maybe even a Laravel component that provides AJAX push functionality?

PS: This AJAX-push-stuff will come in handy in future, I think. A more advance use-case could be collaborative editing a la Google Docs (so that you can see in real-time what someone else is writing within a shared document).

**Comment by devilx** [comment]
Just found another possibility we could use, instead of pure Node.js/Socket.io: http://autobahn.ws/js/
That's an implementation of the WAMP: http://wamp.ws/
