### ISSUE TITLE
Window shopping

### ISSUE THREAD

**Issue by thompsonson** [paperwork/paperwork#67]
Hi,

Just a quick note to say that the concept sounds good but I can't really see the screenshots and the demo requires registration... Maybe worth making it a bit more accessible.

Matt

**Comment by devilx** [comment]
Hi @thompsonson,

thank you! What's the problem with the screenshots? Could you make a screenshot of how it looks for you? Could you right-click one missing image, copy the URL and paste it in here?

The demo requires registration since the product itself is depending on a register user. However, you can enter whatever data you want there, as the registration won't send any e-mails nor will it store this information for more than 24h. As the documentation points out, the database is being purged every day at 3 am in the morning (CET).

Marius

**Comment by Liongold** [comment]
Can't there be a sort of demo account?

**Comment by devilx** [comment]
Well, there could be, although due to quite often database changes in this early stage of development, we would need to permanently adapt this test-account as well. This would result in just another task we would need to take care of when touching the database structure.

Besides, I honestly think that if somebody is really interested in testing Paperwork, it's not a big deal filling out a few input fields and pressing a button. Neither Evernote, nor OneNote nor Google Keep have test account, from what I know. The registration is a feature that people who plan using Paperwork productively will definitely want to test.

**Comment by Liongold** [comment]
Maybe something after 1.0?

**Comment by devilx** [comment]
Well, sure, if this will be a much requested feature after the 1.0 release, we might surely implement some "demo" account, that's free-for-all. With the 1.0 our database layout *should* definitely be more stable.

**Comment by thompsonson** [comment]
Hi,

Cheers for the quick response. I’ve attached to the email - not sure if it’ll work, will post somewhere else if not.



regarding the demo account i must say I’m guilty of a quick scan and then just clicking the link; not really reading anything about the DB or requirements. 

Regards,
Matt

**Comment by devilx** [comment]
@thompsonson unfortunately no attachments came through. Could you upload them either on GitHub or somewhere else and link them? Thank you!

**Comment by thompsonson** [comment]
will do

**Comment by thompsonson** [comment]
I've uploaded it to http://i59.tinypic.com/sfxndf.png - hope that is viewable.

Matt

**Comment by devilx** [comment]
Transferred your Screenshot to github.
![sfxndf](https://cloud.githubusercontent.com/assets/151967/5696921/93ddfff0-99e1-11e4-9ffd-75a520746b58.png)

So what exactly is the issue here? You're actually seeing the screenshots. :-)

**Comment by thompsonson** [comment]
Yes, sorry was’t clear i guess. Images are there just that i can’t read anything on them. 

Matt

**Comment by twoSeats** [comment]
@devilx i would guess that @thompsonson would have preferred a popup of some sort to show the image in it's full size. @thompsonson the image is viewable in full size if you right click and view image though.

**Comment by devilx** [comment]
@twoSeats @thompsonson I see! Will be implemented into the new paperwork.rocks-page.

**Comment by funwhilelost** [comment]
FWIW I set up a private Paperwork in Sandstorm with a couple clicks.  http://oasis.sandstorm.io/
