### ISSUE TITLE
updated from git & now stuck in the /setup.php loop

### ISSUE THREAD

**Issue by doc-jay** [paperwork/paperwork#672]
CENTOS7
 Nginx 1.11.x

I just upgraded my paperwork install from a git pull, did all the updates & now I'm stuck in the setup wizard.  I even have a file 'db_settings' in my /frontend/app/storage folder (no setup file at all) and I still get redirected to the setup wizard.

this worked fine  before I decided to update.  

Any help please?

thank you

**Comment by Liongold** [comment]
Could you include the branch you're using?

Getting redirected is normal because the Setup Wizard was changed. If you want to skip doing it, you can create a file named `setup` and put `8` in it. Then, copy the `default_database.json` and `default_paperwork.json` files and rename them to `databse.json` and `paperwork.json`. Of course, you need to update those files to match your real credentials. These files should be in `frontend/app/storage/config`. Please post if you have any problems.
