### ISSUE TITLE
Can't Share Collection/Notebook in Collection

### ISSUE THREAD

**Issue by HarshNormal** [paperwork/paperwork#763]
I've been playing with Paperwork and have run into a problem:

whenever I or someone else shares a notebook that is inside of a collection, the users to whom I've shared do not see the collection or the notebook, they can only see the notes (which appear in the "All Notes" section.

Is this perhaps an error only I am running into, or has this happened to someone else? I'll troubleshoot more later this week, but can anyone reproduce this?

**Comment by clemlaf** [comment]
This behavious is somewhat intended: when a user shares a note, he does not share the notebook and does not share the private tags. A separate "share Notebook" feature is possible, but not currently implemented in the front-end. However, on backend side, methods for sharing notebooks are implemented.

**Comment by Liongold** [comment]
@clemlaf I'm sorry if I'm asking for too much but do you think you could find the time to implement Share Notebook in the frontend as well, please?

**Comment by clemlaf** [comment]
I think I have a branch with work in that direction on my old computer, I'll try to find some time to start from that and merge with the issue on post requests

**Comment by Liongold** [comment]
Thank you.

**Comment by clemlaf** [comment]
After starting digging into this, I realized that the "Share Notebook" feature was already implement (yet not really visible), since commit 5cd7a5d7.
To share a Notebook, one need to click on the Edit menu, found in the top menu bar. Then, in the modal view, a check box allows to propagate the permissions given at notebook level, to all the notes that are included in the notebook.

![image](https://user-images.githubusercontent.com/11900571/28736538-7ee4b54a-73ea-11e7-9761-b5722499780d.png)

However there is room for improvement on that feature, since it is kind of hidden. For instance one could think of adding this is in the "Manage Notebooks" modal view.

**Comment by Liongold** [comment]
@clemlaf Do you think you could do come up with some ideas and implement them? If you need help, just ask.

**Comment by lujandavid** [comment]
@clemlaf do think you can help us with this, I have a mess in my company due to users can't share their notes. kind regards.

**Comment by mrusme** [comment]
Sharing in v2 will use a different approach, hence this v1 issue is not relevant anymore.
