### ISSUE TITLE
Let's Encrypt and Paperwork

### ISSUE THREAD

**Issue by btafoya** [paperwork/paperwork#827]
Anyone have a rewrite rule I can use to allow Let's Encrypt to work with this app?

Thanks!

**Comment by jsEveryDay** [comment]
Any SSL should work...
What's special or different about Let's Encrypt?

im using self signed cert and no problems. Nginx works like charm.

**Comment by zikeji** [comment]
I think @btafoya might be asking for a rule so Lets Encrypt in webdir mode can renew the cert.

Unfortunately I don't have such a rule for Apache (which it sounds like he is asking for), but on nginx I just use this:

```nginx
location ^~ /.well-known/ {
    allow all;
    default_type "text/plain";
    alias /var/www/acme-challenge/.well-known/;
}
```

Where "alias" is where you've configured your webdir to be. So /var/www/acme-challenge is the webroot as given to letsencrypt in the above example. We append .well-known because that's allow LE cares about.

**Comment by mrusme** [comment]
This is not directly an issue with Paperwork (neither v1 nor v2), as it targets the proxy in front of/httpd hosting Paperwork. Please find information on this on the [official Let's Encrypt documentation](https://letsencrypt.org/getting-started/).
