### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by JoshTGreenwood** [paperwork/paperwork#95]
Is there any interest in adding markdown support to the note body?

**Comment by devilx** [comment]
@JoshTGreenwood right now Paperwork uses the CKEditor. So the most convenient way would probably be, to have a Markdown plugin for the CKEditor, takes the Markdown a user entered and saves it in its regular HTML format, as it does currently with WYSIWYG. When content is being loaded, the CKEditor then would need to transform the saved HTML into Markdown – again, just the way it does with its current WYSIWYG.

Do you know of any ready-to-use-plugin for the CKEditor that could do this?

**Comment by AlJohri** [comment]
Check out this tangentially related project's UI and support for markdown/latex: http://marxi.co

**Comment by yekz** [comment]
thanks for your work

**Comment by mjnaderi** [comment]
I think converting HTML to Markdown is not possible. People want to edit the original plain text they have written, not after converting to html and then from html to Markdown.

This is my idea:

It is better to save in both Markdown and HTML formats. User selects which editor to use (HTML or Markdown).

In HTML case, just save in html format.
In Markdown case, save in both html and markdown formats. When user later edits with html editor, warn the user and remove the saved Markdown (to keep consistency). When user edits Markdown, update both html and markdown.

And it would be nice to use https://github.com/Khan/KaTeX for adding LaTeX support to markdown editor.

**Comment by devilx** [comment]
Thank you guys for the suggestions. Marxi looks cool, but that's only a Markdown editor from what I see.

I like the idea of having Markdown along with traditional WYSIWYG editing. I'm not sure about saving the Markdown separately, though. In worst cases, this would double the size of each note. Plus, we need to consider that content is not being simply saved within the "content"-column of a note-row, inside the database. Instead, for every save that's being performed, a new version is being created, so that people can use the "wayback machine" to travel to a version they might have edited-away. This means, that every version of the note would include two chunks of data: The HTML as it is now and a Markdown chunk.

I believe it's better to implement it in a way, where the content is being stored in a very general format, out of which the note can be rendered afterwards. Additionally to the nearly doubled usage of memory, please also consider, that as soon as Paperwork has something similar to the "Evernote Webclipper", trouble would begin: When a user would clip a web-page (-> HTML), the Markdown chunk would be left blank. When the user then tries to edit the clipped webpage with his Markdown editor, he would see an empty editor, even though the HTML content exists.

This feature needs a bit more overthinking before starting implementation. :-)

**Comment by Baldrs** [comment]
I think you can distinguish the content by adding something like content types, like that:

1. Generic - can be edited using CKEditor(or whatever) and not markdown editor. Here the clipped content goes too.
2. Markdown - can be edited using markdown editor and then converted into generic but not back.

So then you won't have the double content problem, because when the third way(for example LaTEX) will be added, you will not want to add third column for latex only, and also there will no headache with determining what is what.

**Comment by devilx** [comment]
@Baldrs your idea would work perfectly, if there was an editor (like CKEditor) that would support all these different "back-end" formats, but presents them in a common way to the user. But I think that presenting the user a different editor for each content type is a no-go. And: Sooner or later, users will probably expect to be able to "migrate" contents, e.g. from Markdown to HTML/WYSIWYG.

**Comment by Baldrs** [comment]
Unfortunately you cannot just show markdown and **WYSIWYG** editor and then show them in a common way.

From markdown website:

> Markdown is a text-to-HTML conversion tool for web writers. Markdown allows you to write using an easy-to-read, easy-to-write plain text format, then convert it to structurally valid XHTML (or HTML).

So as we see from that definition, markdown is a way of (X)HTML authoring. And that means that **WYSIWYG** and markdown have different philosophies, despite of solving the same thing. And, as consequence of the before, it means it can't be displayed in a common way. 

As a workaround to not frighten the savage users, markdown editor and content-type could be provided as opt-in feature for the power users and enabled somewhere in the settings(or even a module providing this feature).

**Comment by devilx** [comment]
I think we're talking at cross purposes. You are full right with that you said. What I was asking was, whether there is a way, which allows us to save data in one format (preferably HTML, since we'll soon want to clip website, as described above) but let the user edit this format in certain ways: Either raw or filter through a specific "view". One of these views we already provide is the WYSIWYG editing. The second view could be Markdown.

For example projects like https://github.com/domchristie/to-markdown and https://github.com/nickcernis/html-to-markdown are basically trying to implement exactly what I could imagine here. They are "reverse engineering" the input data (HTML) in order to create Markdown out of it.

So, here's my though: Why not search/write a plug-in for the CKEditor which allows users to edit data as Markdown, then stores this Markdown as HTML within the Paperwork database and and, when loading, parses the HTML in order to re-create the Markdown? By that, the user could instantly switch between "Source", "WYSIWYG" and "Markdown" - without Paperwork needing to store three different types of data.

Of course, the "reverse engineering" part will become tricky at that point, where clipped websites should be edited as Markdown. At that point, only items which are representable as Markdown should be displayed/altered. Everything else (like the styling or maybe additional <meta> info) should be retained by the Markdown plug-in, in order to keep the clipped site "working" when viewed through a browser.

What do you think?

**Comment by Baldrs** [comment]
I think contemporary programmer should avoid such magic to fit KISS principle. When converting back to markdown you will definitely lose some data. To reclaim it, you will likely will end up in some additional  "metadata", in workarounds, specific edge case workarounds, bugs, tons of code, etc. Such a converter will definitely will end up in some over-complicated huge monster with lots of extensions, becoming impossible to maintain in the end. Let's try not to implement html again(MS word once tried to store the word documents in html as is. Their product barely managed to recover it, despite they stored lot of metadata inside)

 Things will be worse if you will decide to reinvent as much wheels as possible. CKEditor is complex and bloated enough, and it seems like embedding sourcecode editor inside it for the very beginning is not so trivial as it seems(and they tend to conflict and complicate the things, as well they are heavy).

I agree it is tempting to have all data stored in one place in a generic way, but what if user will want to edit some clipped html in markdown? When I tried to convert article tag of an arstechnica article, to-markdown just took a lot of time to do some conversion and then just converted some links into markdown, leaving everything as it was. CKEditor main WYSIWYG module may handle this, but there could be some magic with the page stylesheets anyway. So here we run into a problem: user can't edit complex html with markdown, nor complex html could be authored with markdown. Therefore we need a way to limit the transitions between markdown and html only to limited html generated with bare CKEditor, and here are the content types. 

So lets sum up:

The approach with complex parser:

Pros:

1. Less tables and columns
2. Easier to get data from database
3. Presumably less storage used

Cons:

1. Complicated code solution
2. Requires CKEditor plugin to be written
3. Requires magic markdown-html binding to maintain different modes(and it is unknown if it is possible to achieve it)

The content-type approach

Pros: 

1. You know well what lies and what is it and how to handle it
2. You don't need to invent any editors or extend some existing with functionality they were never intended for
3. You don't need to write complicated converter
4. Less code to invent - less bugs to fix.

Cons: 

1. Additional database logic to determine content-type or even content-table
2. Additional code modules for each content-type
3. Having different editors for each content-type could be a problem for the users

**Comment by devilx** [comment]
In #190 @joshlemer and I commented on how this could be implemented. I think the best solution for this would be, to add a new column ("type") to the notes table, which defines the note's type. On creation, the user should specifically be able to say, what kind of note he'd like to create. The type should be a fixed length char in order to allow future plugins to extend the note types.

Initially, we would have "html" and "markdown" as type. On a long term, some more types will surely come in handy - for example "document", for notes that shouldn't contain any content besides an attachment (uploaded document).

**Comment by AlJohri** [comment]
If you go with the approach of having a content type column, you may be able to integrate some of the work done on [StackEdit](https://stackedit.io/).

Check out the github here: https://github.com/benweet/stackedit.

**Comment by Baldrs** [comment]
There are some clues I saw today on how we can integrate ckeditor source editor with markdown support, but we will still need some type column.

We somehow need to implement [this](http://nightly-v4.ckeditor.com/ckeditor_api/#!/api/CKEDITOR.dataProcessor), basing on how the bbcode plugin was made.

**Comment by devilx** [comment]
@Baldrs :+1:

**Comment by srphillips** [comment]
May or may not be helpful but found this plugin http://ckeditor.com/addon/markdown

Seems new so may need some more work, but it's a start.  I would also like to see the markdown support.

**Comment by jakov** [comment]
I don't know about the plans for paperwork, but (without knowing any details about the structure of paperworks) i would also vote for markdown as the main input. It's probably easier to handle, since it practically is just plaintext. I'm thinking about versioning and diff for example.

With syntax highlighting like in https://stackedit.io/editor i think one doesn't usually need the HTML preview all the time. It would usually suffice to have a preview on demand (just as here in the comment field for example).

**Comment by mrusme** [comment]
The voices were heard. Paperwork v2 now uses Markdown as its **main markup language**, getting rid of HTML/CKEditor altogether. By keeping the editor more minimal, Paperwork can hopefully provide a better overall experience (with less issues related to editing). The very first shot of that was implemented into [the web UI](https://github.com/paperwork/web) and can be tried by developers eager to get their hands dirty.
